### ISSUE TITLE
can't see draft page when bludit has a custom 404 page set

### ISSUE THREAD

**Issue by Joduai** [pytesNET/draft#1]
Hello
 
Pretty much as topic says.
I found out that every time I want to check page draft I get a 404 page instead.
I didn't get a single warning/notice/error thus I just had to get across most bludit options, and the problem lays in custom 404 page.
If I leave the custom 404 input field empty, draft plugin works.
I wouldn't want to leave a default 404 error page. But I can't disable custom page in options, as the field can't be emptied once set (I have to do it manually in settings dbase).

ps. builtin' bludit preview mode arrived in last commit as for now isn't working, thus your plugin is highly usable :)

**Comment by SamBrishes** [comment]
Hellow,

thanks for reporting this issue. Please try out the new master branch, this issue should be fixed now.

Sincerely,
Sam.

PS.: I really appreciate the core solution, and this plugin will also be removed if 3.9.0 gets released.

**Comment by Joduai** [comment]
Thanks for a lightning fast update.
Everything works now like a charm :)

----

I assume that builtin' preview mode is going to be fixed in 3.9, but for support sake please do not remove this plugin. The more, I hope you will post it under plugins.bludit.com as I believe that many users having =< 3.8.1 will find it useful.

tbh 3.9 would have to come up with something groundbreaking for me to update it.
As for now, with almost all your plugins 3.8.1 is working perfectly 😃

**Comment by SamBrishes** [comment]
Hellow,

No problem, I'm glad that it works now. 

----

That's true... I'll add it to the Plugins directory when I'm back at home (I'm currently at work). :D
